export const airportOptions = [
  { code: 'THE', city: 'Teresina', state: 'PI', name: 'Aeroporto Senador Petronio Portella' },
  { code: 'PHB', city: 'Parnaiba', state: 'PI', name: 'Aeroporto Internacional de Parnaiba' },
  { code: 'NSR', city: 'Sao Raimundo Nonato', state: 'PI', name: 'Aeroporto Serra da Capivara' },
  { code: 'FOR', city: 'Fortaleza', state: 'CE', name: 'Aeroporto Pinto Martins' },
  { code: 'JJD', city: 'Jericoacoara', state: 'CE', name: 'Aeroporto Comandante Ariston Pessoa' },
  { code: 'JDO', city: 'Juazeiro do Norte', state: 'CE', name: 'Aeroporto Orlando Bezerra de Menezes' },
  { code: 'IMP', city: 'Imperatriz', state: 'MA', name: 'Aeroporto Prefeito Renato Moreira' },
  { code: 'SLS', city: 'Sao Luis', state: 'MA', name: 'Aeroporto Marechal Cunha Machado' },
  { code: 'NAT', city: 'Natal', state: 'RN', name: 'Aeroporto Governador Aluizio Alves' },
  { code: 'REC', city: 'Recife', state: 'PE', name: 'Aeroporto Internacional do Recife' },
  { code: 'PNZ', city: 'Petrolina', state: 'PE', name: 'Aeroporto Senador Nilo Coelho' },
  { code: 'FEN', city: 'Fernando de Noronha', state: 'PE', name: 'Aeroporto de Fernando de Noronha' },
]

export const fareFamilies = [
  {
    id: 'leve',
    
    baggage: 'Item pessoal de ate 10kg',
    changePolicy: 'Alteracao com taxa e diferenca tarifaria',
    multiplier: 1,
  },
  {
    id: 'flex',
    baggage: 'Bagagem de mao de 10kg + item pessoal',
    changePolicy: 'Primeira alteracao sem taxa',
    multiplier: 1.22,
  },
  {
    id: 'conforto',
    name: 'Tarifa Conforto',
    description: 'Prioridade, bagagem despachada e assentos dianteiros.',
    baggage: 'Bagagem de mao + 1 mala despachada de 23kg',
    changePolicy: 'Alteracoes flexiveis antes do check-in',
    multiplier: 1.48,
  },
]

export const flightSchedule = [
  {
    id: 'NA2101',
    flightNumber: 'NA 2101',
    origin: 'THE',
    destination: 'REC',
    departureTime: '06:15',
    arrivalTime: '08:00',
    duration: '1h45',
    aircraft: 'Embraer E195-E2',
    basePrice: 389,
  },
  {
    id: 'NA2102',
    flightNumber: 'NA 2102',
    origin: 'REC',
    destination: 'THE',
    departureTime: '18:40',
    arrivalTime: '20:20',
    duration: '1h40',
    aircraft: 'Embraer E195-E2',
    basePrice: 379,
  },
  {
    id: 'NA2307',
    flightNumber: 'NA 2307',
    origin: 'FOR',
    destination: 'FEN',
    departureTime: '09:30',
    arrivalTime: '11:25',
    duration: '1h55',
    aircraft: 'Airbus A220-300',
    basePrice: 624,
  },
  {
    id: 'NA2308',
    flightNumber: 'NA 2308',
    origin: 'FEN',
    destination: 'FOR',
    departureTime: '15:50',
    arrivalTime: '17:35',
    duration: '1h45',
    aircraft: 'Airbus A220-300',
    basePrice: 612,
  },
  {
    id: 'NA2410',
    flightNumber: 'NA 2410',
    origin: 'SLS',
    destination: 'FOR',
    departureTime: '07:10',
    arrivalTime: '08:35',
    duration: '1h25',
    aircraft: 'Embraer E190-E2',
    basePrice: 331,
  },
  {
    id: 'NA2411',
    flightNumber: 'NA 2411',
    origin: 'FOR',
    destination: 'SLS',
    departureTime: '19:05',
    arrivalTime: '20:25',
    duration: '1h20',
    aircraft: 'Embraer E190-E2',
    basePrice: 329,
  },
  {
    id: 'NA2520',
    flightNumber: 'NA 2520',
    origin: 'NAT',
    destination: 'REC',
    departureTime: '12:25',
    arrivalTime: '13:25',
    duration: '1h00',
    aircraft: 'ATR 72-600',
    basePrice: 245,
  },
  {
    id: 'NA2521',
    flightNumber: 'NA 2521',
    origin: 'REC',
    destination: 'NAT',
    departureTime: '16:45',
    arrivalTime: '17:45',
    duration: '1h00',
    aircraft: 'ATR 72-600',
    basePrice: 249,
  },
  {
    id: 'NA2603',
    flightNumber: 'NA 2603',
    origin: 'PHB',
    destination: 'FOR',
    departureTime: '10:05',
    arrivalTime: '11:15',
    duration: '1h10',
    aircraft: 'ATR 72-600',
    basePrice: 288,
  },
  {
    id: 'NA2604',
    flightNumber: 'NA 2604',
    origin: 'FOR',
    destination: 'PHB',
    departureTime: '13:20',
    arrivalTime: '14:30',
    duration: '1h10',
    aircraft: 'ATR 72-600',
    basePrice: 294,
  },
  {
    id: 'NA2705',
    flightNumber: 'NA 2705',
    origin: 'IMP',
    destination: 'REC',
    departureTime: '05:55',
    arrivalTime: '08:10',
    duration: '2h15',
    aircraft: 'Embraer E190-E2',
    basePrice: 448,
  },
  {
    id: 'NA2706',
    flightNumber: 'NA 2706',
    origin: 'REC',
    destination: 'IMP',
    departureTime: '20:35',
    arrivalTime: '22:45',
    duration: '2h10',
    aircraft: 'Embraer E190-E2',
    basePrice: 452,
  },
  {
    id: 'NA2809',
    flightNumber: 'NA 2809',
    origin: 'JJD',
    destination: 'FOR',
    departureTime: '17:15',
    arrivalTime: '18:10',
    duration: '0h55',
    aircraft: 'ATR 72-600',
    basePrice: 219,
  },
  {
    id: 'NA2810',
    flightNumber: 'NA 2810',
    origin: 'FOR',
    destination: 'JJD',
    departureTime: '08:15',
    arrivalTime: '09:10',
    duration: '0h55',
    aircraft: 'ATR 72-600',
    basePrice: 225,
  },
]

export const serviceHighlights = [
  {
    title: 'Rotas regionais conectadas',
    text: 'Malha desenhada para aproximar capitais, litoral e polos de turismo no Nordeste.',
  },
  {
    title: 'Jornada digital completa',
    text: 'Busca, reserva, emissao, consulta, check-in e servicos extras no mesmo portal.',
  },
  {
    title: 'Atendimento com identidade local',
    text: 'Uma companhia brasileira com operacao simples, linguagem clara e foco no passageiro.',
  },
]

export const destinationCards = [
  {
    city: 'Jericoacoara',
    category: 'Praia e vento',
    description: 'Voos com conexao por Fortaleza para quem combina kitesurf, dunas e descanso.',
  },
  {
    city: 'Sao Luis',
    category: 'Cultura e gastronomia',
    description: 'Centro historico, azulejos, festas populares e cozinha marcante do litoral maranhense.',
  },
  {
    city: 'Fernando de Noronha',
    category: 'Escapada premium',
    description: 'Operacao sazonal com disponibilidade controlada para preservar uma experiencia exclusiva.',
  },
]

export const destinationProfiles = {
  praia: ['Jericoacoara', 'Natal', 'Fernando de Noronha'],
  cultura: ['Sao Luis', 'Recife', 'Teresina'],
  natureza: ['Sao Raimundo Nonato', 'Parnaiba', 'Fernando de Noronha'],
  negocios: ['Fortaleza', 'Recife', 'Imperatriz'],
}

export const stopoverCities = [
  { code: 'FOR', city: 'Fortaleza', maxNights: 3 },
  { code: 'REC', city: 'Recife', maxNights: 3 },
  { code: 'SLS', city: 'Sao Luis', maxNights: 2 },
  { code: 'NAT', city: 'Natal', maxNights: 2 },
]

export const hotelCities = ['Jericoacoara', 'Fortaleza', 'Recife', 'Sao Luis', 'Natal']
